insert into Preassigns values("jadamson", "Justin Perez Adamson", 0);
insert into Preassigns values("vanorve", "Veronica Francesca Anorve", 0);
insert into Preassigns values("surabhi2", "Surabhi Balachander", 0);
insert into Preassigns values("gbarajas", "Gabriel Ivan Barajas", 0);
insert into Preassigns values("jjbeed", "Justine Julia Beed", 0);
insert into Preassigns values("jcarpent", "Joe H Carpenter", 0);
insert into Preassigns values("hcaseyal", "Hope Kim Fong Casey-Allen", 0);
insert into Preassigns values("jacasey", "Jace Alexander Casey", 0);
insert into Preassigns values("mcsforza", "Manni Luca Giovanni Cavalli-Sforza", 0);
insert into Preassigns values("rzcheng", "Robin Cheng", 0);
insert into Preassigns values("alexcr", "Alexandros Christodoulou-Rubalcava", 0);
insert into Preassigns values("cjmg", "Gloria Chua Jia Min", 0);
insert into Preassigns values("bccortez", "Brandon Christopher Cortez", 0);
insert into Preassigns values("dienhart", "Dustin Dienhart", 0);
insert into Preassigns values("marinadi", "Marina Alexander Dimitrov", 0);
insert into Preassigns values("rcduncan", "Ryan Christian Duncan", 0);
insert into Preassigns values("redlin", "Rylan Joseph Edlin", 0);
insert into Preassigns values("danfan17", "Dan Fan", 0);
insert into Preassigns values("gla", "Alec Song Glassford", 0);
insert into Preassigns values("jason7", "Jason Heemang Griffin", 0);
insert into Preassigns values("dguo1113", "Dan Guo", 0);
insert into Preassigns values("sher820", "Selina Her", 0);
insert into Preassigns values("diegoh", "Diego Bordeos Hernandez", 0);
insert into Preassigns values("arahana", "Audrey Hana Hsu", 0);
insert into Preassigns values("irvhsu", "Irving Hsu", 0);
insert into Preassigns values("benjin18", "Benjamin Edward Jin", 0);
insert into Preassigns values("jkim21", "Daniella Kim", 0);
insert into Preassigns values("ckimzey", "Colin James Kimzey", 0);
insert into Preassigns values("akumar03", "Ashwin Kumar", 0);
insert into Preassigns values("hjkwon93", "Mark Kwon", 0);
insert into Preassigns values("chengshu", "Eric Li", 0);
insert into Preassigns values("jylum", "Jian Yang Lum", 0);
insert into Preassigns values("joseph23", "Joseph Haleem Maalouf", 0);
insert into Preassigns values("amestas", "Arthur Joseph Mestas", 0);
insert into Preassigns values("ptohare", "Patrick Taylor O'Hare", 0);
insert into Preassigns values("allison9", "Allison Gale Perry", 0);
insert into Preassigns values("shrcor", "Scott Henry Reid", 0);
insert into Preassigns values("jaxwr", "Jackson Wiley Roach", 0);
insert into Preassigns values("evelyro1", "Evelyn Rodriguez", 0);
insert into Preassigns values("raquelos", "Raquel Raquel Orendain Shrestha", 0);
insert into Preassigns values("dsmith4", "Danielle Alexis Smith", 0);
insert into Preassigns values("teisberg", "Thomas Olmsted Teisberg", 0);
insert into Preassigns values("camille1", "Camille Louise Lamarre Townshend", 0);
insert into Preassigns values("cuhm", "Chae Young Uhm", 0);
insert into Preassigns values("avan994", "Anthony Van", 0);
insert into Preassigns values("krysten", "Krysten Ann Walker", 0);
insert into Preassigns values("wangye", "Ye Wang", 0);
insert into Preassigns values("jlwatson", "Jean-Luc Christopher Watson", 0);
insert into Preassigns values("jwwest", "John Ward West", 0);
insert into Preassigns values("duncanw", "Duncan Gerner Wood", 0);
insert into Preassigns values("czhao95", "Carol Yiyu Zhao", 0);
